import {createClient} from '@supabase/supabase-js';
import {Html5Qrcode} from 'html5-qrcode';
import QRCode from 'qrcode';
import './style.css';
const sb=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_ANON_KEY),app=document.querySelector('#app');
let items=[],moves=[]; const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),unit=i=>i.unit==='box'?'boxes':i.unit==='pack'?'packs':i.unit;
const st=i=>!i.par_level?['unset','Par not set']:i.current_stock<=i.reorder_level?['out','Reorder']:i.current_stock<i.par_level?['low','Below par']:['ok','OK'];
async function load(){let a=await sb.from('inventory_items').select('*').eq('active',true).order('category').order('name');if(a.error)return err(a.error.message);items=a.data||[];let b=await sb.from('stock_movements').select('*,inventory_items(name,unit)').order('created_at',{ascending:false}).limit(100);moves=b.data||[];draw()}
function err(x){app.innerHTML=`<main class="center"><div class="notice error">${esc(x)}</div></main>`}
function draw(){let att=items.filter(i=>['out','low'].includes(st(i)[0])).length,out=items.filter(i=>st(i)[0]==='out').length;app.innerHTML=`<header><div><b>KENILWORTH</b><small>Storeroom Stock</small></div><button id="logout">Log out</button></header><main><button class="scan" id="scan">📷 SCAN QR ITEM</button><div class="summary"><div><b>${att}</b><small>need attention</small></div><div><b>${out}</b><small>at reorder</small></div><div><b>${items.length}</b><small>active items</small></div></div><div class="grid"><button id="rec">➕<small>Receive</small></button><button id="rem" class="danger">➖<small>Remove</small></button><button id="cnt">🔢<small>Stock Count</small></button><button id="low">🔴<small>Low Stock</small></button></div><section><div class="row"><h3>Stock health</h3><span>${att?att+' need attention':'All stock healthy'}</span></div>${items.map(row).join('')}</section><section><div class="row"><h3>Restock list</h3><button id="orders" class="link">Manage orders</button></div>${restock()}</section><section><div class="row"><h3>Recent movement</h3><button id="hist" class="link">View all</button></div>${moves.slice(0,5).map(mrow).join('')||'<p>No movements yet.</p>'}</section><section><h3>Management</h3><button id="qr" class="wide">▣ QR Code Labels</button><button id="add" class="wide">＋ Add new item</button></section></main>`;
logout.onclick=()=>sb.auth.signOut();scan.onclick=scanQR;rec.onclick=()=>choose('receive');rem.onclick=()=>choose('remove');cnt.onclick=()=>choose('count');low.onclick=lowStock;hist.onclick=historyView;orders.onclick=orderManager;qr.onclick=qrManager;add.onclick=addItem;document.querySelectorAll('[data-id]').forEach(x=>x.onclick=()=>manage(x.dataset.id))}
function row(i){let s=st(i),d=i.last_counted_at?new Date(i.last_counted_at).toLocaleDateString():'Never';return `<div class="item"><div class="row"><div><b>${esc(i.name)}</b><small>${esc(i.category)} · ${unit(i)}${i.shared_group?' · shared lid':''}</small></div><span class="pill ${s[0]}">${s[1]}</span></div><div class="stock"><strong>${i.current_stock}</strong><span>Par ${i.par_level||'—'} · Reorder ${i.reorder_level||'—'}</span><button data-id="${i.id}">Manage</button></div><small>Last counted: ${d}</small></div>`}
function mrow(m){return `<div class="move"><b>${esc(m.action.replaceAll('_',' '))}</b> · ${esc(m.quantity??'')} · ${esc(m.inventory_items?.name)}${m.reason?' · '+esc(m.reason):''}<small>${new Date(m.created_at).toLocaleString()}</small></div>`}
function restock(){let x=items.filter(i=>['out','low'].includes(st(i)[0]));return x.length?x.slice(0,5).map(i=>`<div class="restock"><b>${esc(i.name)}</b><span>Need ${Math.max(0,i.par_level-i.current_stock)} ${unit(i)}</span></div>`).join(''):'<div class="notice">Nothing needs ordering right now.</div>'}
function modal(h){let d=document.createElement('div');d.className='modal';d.innerHTML=`<div class="sheet">${h}</div>`;document.body.append(d);return d} const close=d=>d.remove();
function choose(a){let title=a==='receive'?'Receive stock':a==='remove'?'Remove stock':'Physical stock count',d=modal(`<h2>${title}</h2>${items.map(i=>`<button class="choice" data-x="${i.id}"><span>${esc(i.name)}</span><span>${i.current_stock} ${unit(i)}</span></button>`).join('')}<button id="x" class="wide">Cancel</button>`);d.querySelector('#x').onclick=()=>close(d);d.querySelectorAll('[data-x]').forEach(x=>x.onclick=()=>{close(d);actionItem(x.dataset.x,a)})}
async function actionItem(id,a){let i=items.find(x=>x.id===id),count=a==='count',remove=a==='remove',d=modal(`<h2>${count?'Physical stock count':remove?'Remove stock':'Receive stock'}</h2><p><b>${esc(i.name)}</b><br>Current: ${i.current_stock} ${unit(i)}</p><label>${count?'Physical quantity':'Quantity'}</label><input id="q" class="input" type="number" min="0" value="${count?i.current_stock:1}">${remove?'<label>Reason</label><select id="reason" class="input"><option>Store usage</option><option>Transfer</option><option>Damaged</option><option>Incorrect count</option><option>Other</option></select>':''}<button id="ok" class="primary wide">Confirm</button><button id="x" class="wide">Cancel</button>`);d.querySelector('#x').onclick=()=>close(d);d.querySelector('#ok').onclick=async()=>{let q=Number(d.querySelector('#q').value),old=i.current_stock,n=count?q:remove?old-q:old+q;if(!Number.isInteger(q)||q<0||n<0)return alert('Invalid quantity.');let u=await sb.auth.getUser(),e=await sb.from('inventory_items').update({current_stock:n,updated_at:new Date().toISOString(),...(count?{last_counted_at:new Date().toISOString()}: {})}).eq('id',id);if(e.error)return alert(e.error.message);e=await sb.from('stock_movements').insert({store_id:i.store_id,item_id:id,action:count?'count_adjust':a,quantity:q,previous_stock:old,new_stock:n,reason:d.querySelector('#reason')?.value||null,user_id:u.data.user?.id});if(e.error)return alert(e.error.message);close(d);load()}}
function manage(id){let i=items.find(x=>x.id===id),d=modal(`<h2>${esc(i.name)}</h2><div class="heroStock"><strong>${i.current_stock}</strong><span>${unit(i)}</span></div><div class="notice">Par: <b>${i.par_level||'not set'}</b> · Reorder: <b>${i.reorder_level||'not set'}</b><br>Last counted: <b>${i.last_counted_at?new Date(i.last_counted_at).toLocaleDateString():'Never'}</b></div><div class="grid"><button id="r">➕<small>Receive</small></button><button id="o" class="danger">➖<small>Remove</small></button><button id="c">🔢<small>Count</small></button><button id="p">⚙️<small>Par levels</small></button></div><button id="x" class="wide">Close</button>`);d.querySelector('#r').onclick=()=>{close(d);actionItem(id,'receive')};d.querySelector('#o').onclick=()=>{close(d);actionItem(id,'remove')};d.querySelector('#c').onclick=()=>{close(d);actionItem(id,'count')};d.querySelector('#p').onclick=()=>levels(id);d.querySelector('#x').onclick=()=>close(d)}
function levels(id){let i=items.find(x=>x.id===id),d=modal(`<h2>Par levels</h2><p><b>${esc(i.name)}</b></p><label>Par level</label><input id="p" class="input" type="number" min="0" value="${i.par_level}"><label>Reorder level</label><input id="r" class="input" type="number" min="0" value="${i.reorder_level}"><button id="s" class="primary wide">Save</button><button id="x" class="wide">Cancel</button>`);d.querySelector('#x').onclick=()=>close(d);d.querySelector('#s').onclick=async()=>{let p=Number(d.querySelector('#p').value),r=Number(d.querySelector('#r').value);if(r>p)return alert('Reorder level cannot exceed par.');let e=await sb.from('inventory_items').update({par_level:p,reorder_level:r}).eq('id',id);if(e.error)alert(e.error.message);else{close(d);load()}}}
function lowStock(){let x=items.filter(i=>['out','low'].includes(st(i)[0])),d=modal(`<h2>Low Stock</h2>${x.length?x.map(row).join(''):'<div class="notice">No items are below par.</div>'}<button id="x" class="wide">Close</button>`);d.querySelector('#x').onclick=()=>close(d)}
function orderManager(){let x=items.filter(i=>['out','low'].includes(st(i)[0])),d=modal(`<h2>Restock / Order List</h2><p>Suggested quantity brings each item back to par.</p>${x.length?x.map(i=>`<div class="orderItem"><div><b>${esc(i.name)}</b><small>Current ${i.current_stock} · Par ${i.par_level}</small></div><button data-o="${i.id}">${i.order_status==='ordered'?'✓ Ordered':'Mark ordered'}</button></div>`).join(''):'<div class="notice">Nothing to order.</div>'}<button id="x" class="wide">Close</button>`);d.querySelector('#x').onclick=()=>close(d);d.querySelectorAll('[data-o]').forEach(b=>b.onclick=async()=>{let i=items.find(x=>x.id===b.dataset.o);await sb.from('inventory_items').update({order_status:i.order_status==='ordered'?'none':'ordered'}).eq('id',i.id);close(d);load()})}
function historyView(){let d=modal(`<h2>Movement History</h2><div class="filters"><button data-f="all">All</button><button data-f="receive">Received</button><button data-f="remove">Removed</button><button data-f="count_adjust">Counts</button></div><div id="ml">${moves.map(mrow).join('')||'<p>No movements.</p>'}</div><button id="x" class="wide">Close</button>`);d.querySelector('#x').onclick=()=>close(d);d.querySelectorAll('[data-f]').forEach(b=>b.onclick=()=>{let f=b.dataset.f;d.querySelector('#ml').innerHTML=moves.filter(m=>f==='all'||m.action===f).map(mrow).join('')||'<p>No movements.</p>'})}
async function addItem(){let d=modal(`<h2>Add item</h2><input id="n" class="input" placeholder="Item name"><input id="c" class="input" placeholder="Category"><select id="u" class="input"><option value="box">Box</option><option value="pack">Pack</option></select><button id="s" class="primary wide">Add</button><button id="x" class="wide">Cancel</button>`);d.querySelector('#x').onclick=()=>close(d);d.querySelector('#s').onclick=async()=>{let name=d.querySelector('#n').value.trim(),cat=d.querySelector('#c').value.trim(),store=(await sb.from('stores').select('id').eq('name','Kenilworth').single()).data;if(!name||!cat||!store)return alert('Enter all details.');let e=await sb.from('inventory_items').insert({store_id:store.id,name,category:cat,unit:d.querySelector('#u').value});if(e.error)alert(e.error.message);else{close(d);load()}}}
async function qrManager(){let d=modal(`<h2>QR Code Labels</h2><p>Print one label for each physical item.</p><div id="qrl">${items.map(i=>`<div class="qrItem"><div><b>${esc(i.name)}</b><small>${esc(i.category)}</small></div><button data-q="${i.id}">View / Print</button></div>`).join('')}</div><button id="x" class="wide">Close</button>`);d.querySelector('#x').onclick=()=>close(d);d.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>showQR(b.dataset.q))}
async function showQR(id){let i=items.find(x=>x.id===id),d=modal(`<div class="label"><h2>KENILWORTH</h2><h1>${esc(i.name)}</h1><div id="qrimg"></div><p>SCAN TO MANAGE STOCK</p></div><button id="print" class="primary wide">🖨 Print Label</button><button id="x" class="wide">Back</button>`);d.querySelector('#x').onclick=()=>close(d);let c=document.createElement('canvas');await QRCode.toCanvas(c,String(i.qr_token),{width:220,margin:2});d.querySelector('#qrimg').append(c);d.querySelector('#print').onclick=()=>{let w=open('','print');w.document.write(`<html><body style="font-family:Arial;text-align:center;padding:30px"><div style="border:2px solid #222;padding:20px;width:300px;margin:auto"><h2>KENILWORTH</h2><h1>${esc(i.name)}</h1><img src="${c.toDataURL()}"><p><b>SCAN TO MANAGE STOCK</b></p></div><script>print()<\/script></body></html>`);w.document.close()}}
async function scanQR(){let d=modal(`<h2>Scan QR Item</h2><div id="reader"></div><button id="x" class="wide">Cancel</button>`),s=new Html5Qrcode('reader');d.querySelector('#x').onclick=()=>{s.stop().catch(()=>{});close(d)};try{await s.start({facingMode:'environment'},{fps:10,qrbox:220},async text=>{let i=items.find(x=>String(x.qr_token)===String(text));if(!i)return alert('QR not recognised.');await s.stop();close(d);manage(i.id)})}catch(e){d.querySelector('#reader').innerHTML='<div class="notice error">Camera access failed. Allow camera permission.</div>'}}
function login(){app.innerHTML=`<main class="login"><div class="loginCard"><h1>Kenilworth</h1><p>Storeroom Stock</p><input id="e" class="input" type="email" placeholder="Manager email"><input id="p" class="input" type="password" placeholder="Password"><button id="in" class="primary wide">Log in</button><div id="err"></div></div></main>`;document.querySelector('#in').onclick=async()=>{let e=await sb.auth.signInWithPassword({email:document.querySelector('#e').value,password:document.querySelector('#p').value});if(e.error)document.querySelector('#err').textContent=e.error.message}}
sb.auth.onAuthStateChange((_e,s)=>s?load():login());
