
import {createClient} from "@supabase/supabase-js";
import {Html5Qrcode} from "html5-qrcode";
import "./style.css";
const sb=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_ANON_KEY);
let items=[],moves=[];
const app=document.querySelector("#app"), esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const stat=i=>i.par_level===0?["ok","Par not set"]:i.current_stock<=i.reorder_level?["out","Reorder"]:i.current_stock<i.par_level?["low","Below par"]:["ok","OK"];
const unit=i=>i.unit==="box"?"boxes":"packs";
async function load(){
 const a=await sb.from("inventory_items").select("*").eq("active",true).order("category").order("name"); items=a.data||[];
 const b=await sb.from("stock_movements").select("*,inventory_items(name,unit)").order("created_at",{ascending:false}).limit(50); moves=b.data||[];
 draw();
}
function draw(){
 const attention=items.filter(i=>stat(i)[0]!=="ok").length;
 app.innerHTML=`<header><div><b>KENILWORTH</b><small>Storeroom Stock</small></div><button id="logout">Log out</button></header><main>
 <button class="scan" id="scan">📷 Scan QR Item</button>
 <div class="grid"><button id="rec">➕<small>Receive</small></button><button id="rem" class="danger">➖<small>Remove</small></button><button id="cnt">🔢<small>Stock Count</small></button><button id="low">🔴<small>Low Stock</small></button></div>
 <section><div class="row"><h3>Stock health</h3><span>${attention} need attention</span></div>${items.map(row).join("")}</section>
 <section><div class="row"><h3>Recent movement</h3><button id="hist" class="link">View all</button></div>${moves.slice(0,5).map(m=>`<div class="move"><b>${esc(m.action)}</b> · ${esc(m.quantity)} · ${esc(m.inventory_items?.name)}</div>`).join("")||"<p>No movements yet.</p>"}</section>
 <section><h3>Management</h3><button id="add" class="wide">＋ Add new item</button></section></main>`;
 logout.onclick=()=>sb.auth.signOut();scan.onclick=()=>scanQR();rec.onclick=()=>choose("receive");rem.onclick=()=>choose("remove");cnt.onclick=()=>choose("count");low.onclick=lowStock;hist.onclick=historyView;add.onclick=addItem;
 document.querySelectorAll("[data-id]").forEach(x=>x.onclick=()=>manage(x.dataset.id));
}
function row(i){let s=stat(i);return `<div class="item"><div class="row"><div><b>${esc(i.name)}</b><small>${esc(i.category)} · ${unit(i)}${i.shared_group?" · shared lid":""}</small></div><span class="pill ${s[0]}">${s[1]}</span></div><div class="stock"><strong>${i.current_stock}</strong><span>Par ${i.par_level||"—"} · Reorder ${i.reorder_level||"—"}</span><button data-id="${i.id}">Manage</button></div></div>`}
function modal(h){let d=document.createElement("div");d.className="modal";d.innerHTML=`<div class="sheet">${h}</div>`;document.body.append(d);return d}
function close(d){d.remove()}
function choose(action){let d=modal(`<h2>${action==="receive"?"Receive":action==="remove"?"Remove":"Count"} stock</h2>${items.map(i=>`<button class="choice" data-x="${i.id}">${esc(i.name)}<span>${i.current_stock} ${i.unit}</span></button>`).join("")}<button id="x" class="wide">Cancel</button>`);d.querySelector("#x").onclick=()=>close(d);d.querySelectorAll("[data-x]").forEach(x=>x.onclick=()=>{close(d);actionItem(x.dataset.x,action)})}
function manage(id){let i=items.find(x=>x.id===id),d=modal(`<h2>${esc(i.name)}</h2><div class="notice">Current stock: <b>${i.current_stock} ${unit(i)}</b></div><div class="grid"><button id="r">➕<small>Receive</small></button><button id="o" class="danger">➖<small>Remove</small></button><button id="c">🔢<small>Count</small></button><button id="p">⚙️<small>Par levels</small></button></div><button id="x" class="wide">Close</button>`);d.querySelector("#r").onclick=()=>{close(d);actionItem(id,"receive")};d.querySelector("#o").onclick=()=>{close(d);actionItem(id,"remove")};d.querySelector("#c").onclick=()=>{close(d);actionItem(id,"count")};d.querySelector("#p").onclick=()=>levels(id);d.querySelector("#x").onclick=()=>close(d)}
async function actionItem(id,action){let i=items.find(x=>x.id===id),d=modal(`<h2>${action==="receive"?"Receive":action==="remove"?"Remove":"Physical count"}</h2><p><b>${esc(i.name)}</b><br>Current: ${i.current_stock} ${unit(i)}</p><input id="q" class="input" type="number" min="0" value="${action==="count"?i.current_stock:1}"><button id="ok" class="primary wide">Confirm</button><button id="x" class="wide">Cancel</button>`);d.querySelector("#x").onclick=()=>close(d);d.querySelector("#ok").onclick=async()=>{let q=Number(d.querySelector("#q").value),old=i.current_stock,n=action==="receive"?old+q:action==="remove"?old-q:q;if(q<0||n<0)return alert("Invalid quantity.");let u=await sb.auth.getUser();let e=await sb.from("inventory_items").update({current_stock:n,updated_at:new Date().toISOString()}).eq("id",id);if(e.error)return alert(e.error.message);await sb.from("stock_movements").insert({store_id:i.store_id,item_id:id,action:action==="count"?"count_adjust":action,quantity:q,previous_stock:old,new_stock:n,user_id:u.data.user?.id});close(d);load()}}
function levels(id){let i=items.find(x=>x.id===id),d=modal(`<h2>Par levels</h2><p><b>${esc(i.name)}</b></p><label>Par</label><input id="p" class="input" type="number" min="0" value="${i.par_level}"><label>Reorder</label><input id="r" class="input" type="number" min="0" value="${i.reorder_level}"><button id="s" class="primary wide">Save</button><button id="x" class="wide">Cancel</button>`);d.querySelector("#x").onclick=()=>close(d);d.querySelector("#s").onclick=async()=>{let e=await sb.from("inventory_items").update({par_level:Number(d.querySelector("#p").value)||0,reorder_level:Number(d.querySelector("#r").value)||0}).eq("id",id);if(e.error)alert(e.error.message);else{close(d);load()}}}
function lowStock(){let x=items.filter(i=>i.par_level&&i.current_stock<=i.par_level),d=modal(`<h2>Low Stock</h2>${x.length?x.map(row).join(""):"<div class='notice'>No items are below par.</div>"}<button id="x" class="wide">Close</button>`);d.querySelector("#x").onclick=()=>close(d)}
function historyView(){let d=modal(`<h2>Movement History</h2>${moves.map(m=>`<div class="move"><b>${esc(m.action)}</b> · ${esc(m.quantity)} · ${esc(m.inventory_items?.name)}<small>${new Date(m.created_at).toLocaleString()}</small></div>`).join("")||"<p>No movements yet.</p>"}<button id="x" class="wide">Close</button>`);d.querySelector("#x").onclick=()=>close(d)}
function addItem(){let d=modal(`<h2>Add item</h2><input id="n" class="input" placeholder="Item name"><input id="c" class="input" placeholder="Category"><select id="u" class="input"><option value="box">Box</option><option value="pack">Pack</option></select><button id="s" class="primary wide">Add</button><button id="x" class="wide">Cancel</button>`);d.querySelector("#x").onclick=()=>close(d);d.querySelector("#s").onclick=async()=>{let st=(await sb.from("stores").select("id").eq("name","Kenilworth").single()).data,e=await sb.from("inventory_items").insert({store_id:st.id,name:d.querySelector("#n").value,category:d.querySelector("#c").value,unit:d.querySelector("#u").value});if(e.error)alert(e.error.message);else{close(d);load()}}}
async function scanQR(){let d=modal(`<h2>Scan QR</h2><div id="reader"></div><button id="x" class="wide">Cancel</button>`),scanner=new Html5Qrcode("reader");d.querySelector("#x").onclick=()=>{scanner.stop().catch(()=>{});close(d)};try{await scanner.start({facingMode:"environment"},{fps:10,qrbox:220},async text=>{let i=items.find(x=>x.qr_token===text);if(!i)return alert("QR not recognised.");await scanner.stop();close(d);manage(i.id)})}catch(e){document.querySelector("#reader").innerHTML="<div class='notice'>Camera access failed. Allow camera permission and try again.</div>"}}
function login(){app.innerHTML=`<main class="login"><div class="loginCard"><h1>Kenilworth</h1><p>Storeroom Stock</p><input id="e" class="input" type="email" placeholder="Manager email"><input id="p" class="input" type="password" placeholder="Password"><button id="in" class="primary wide">Log in</button><div id="err"></div></div></main>`;document.querySelector("#in").onclick=async()=>{let e=await sb.auth.signInWithPassword({email:document.querySelector("#e").value,password:document.querySelector("#p").value});if(e.error)document.querySelector("#err").textContent=e.error.message}}
sb.auth.onAuthStateChange((_e,s)=>s?load():login());
